### ISSUE TITLE
Add an example service with both minimal backend and frontend

### ISSUE THREAD

**Issue by umputun** [go-pkgz/auth#1]
The goal is to make a demo service doing something very simple but demonstrating end-to-end usage of the library.

I'm going to make top-level `example` directory for this and will have it as a fully automated build producing docker image. The final container with everything in will run somewhere in DO.

@Reeywhaar - how about UI side, can I count on you? Need smth really trivial, maybe a couple of "pages" to demonstrate access to protected resources with login via all providers. If you willing to help I'll give you more details.

**Comment by Reeywhaar** [comment]
@umputun okay, I'm in, nothing hard here, I guess.

**Comment by umputun** [comment]
thx. yeah, should be really trivial thingy

**Comment by umputun** [comment]
@Reeywhaar all yours.

Under `_example` there is an ... example. `docker-compose build && docker compose up` to start the thing. It will listen on http://127.0.0.1:8080 to "/public" and "/private" (both generated by the server).  Private rejects till you do auth. i.e. http://127.0.0.1:8080/auth/dev/login?from=/private

All API (just a few calls) described in [API section](https://github.com/go-pkgz/auth#api)

I just need an example of SPA demoing smth with protected resource `/private_data`. Something simple but not too ugly, up to you. And speaking of ugly - if you can also de-uglify the [login form](https://github.com/go-pkgz/auth/blob/master/provider/dev_provider.go#L179) I made for dev auth server - it will be very nice of you.

one more thing - this web app should do XSRF header trick, i.e. send back `X-XSRF-TOKEN` header with cookie value from XSRF-TOKEN.

**Comment by Reeywhaar** [comment]
@umputun got it, already there. I'll ping if something not clear.
