### ISSUE TITLE
Bug: (/_example) Using "Login with custom_123" results in "Invalid Request"

### ISSUE THREAD

**Issue by chowieuk** [go-pkgz/auth#130]
Thanks for all the great work on this library.

This is my first issue, so apologies if I've missed the mark or omitted something. Constructive criticism is appreciated.

Version: master v1.18.0
Browser: Chrome Version 106.0.5249.103 (Official Build) (64-bit)

Problem: When running the example and choosing "Login with custom_123", entering the credentials provided results in an invalid request.

Steps:

- git clone `https://github.com/go-pkgz/auth/`
- cd /auth/_example
- go mod tidy
- go run main.go
- open `http://localhost:8080/web/` in a browser
- click `Login with custom123`
- enter `admin` as username
- enter `admin `password
- click authorize

Expectation:

You are redirected to http://localhost:8080/web/ and are authorized using the custom provider

Result:

"Invalid Request"

Notes:

Replacing the action attribute of the form element present on `http://127.0.0.1:9096/authorize..` with a URL decoded version results in success.

This is what the <form> element looks like when inspecting `http://127.0.0.1:9096/authorize...` (the custom oauth2 server)

`<form action="/login/oauth/authorize?client_id%3dcid%26redirect_uri%3dhttp%253A%252F%252Flocalhost%253A8080%252Fauth%252Fcustom123%252Fcallback%26response_type%3dcode%26state%3dd11e3e82d573eb897c28e8ed47f5798c791e15b5" method="POST">`

If I edit the action attribute and and decode it via https://meyerweb.com/eric/tools/dencoder/

I get the following:

`/login/oauth/authorize?client_id=cid&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2Fauth%2Fcustom123%2Fcallback&response_type=code&state=d11e3e82d573eb897c28e8ed47f5798c791e15b5`

If I replace the original form action with the above then the form submission works as expected.

**Comment by paskal** [comment]
Could you please verify if it works on http://127.0.0.1/web/ ? It's a known problem that 127.0.0.1 works and localhost doesn't because of the way it's set up, and I wrote it down in remark42 documentation but forgot to update this library documentation it seems.

**Comment by Zhomart** [comment]
Just verified. It doesn't work for both `127.0.0.1` and `localhost`. 

![image](https://user-images.githubusercontent.com/830536/212462339-57d9f3b5-7621-49df-a5a1-da79eaee850f.png)
