### ISSUE TITLE
Password in GET is Insecure

### ISSUE THREAD

**Issue by guettli** [go-pkgz/auth#133]
From the README:

> GET /auth/<name>/login?user=<user>&passwd=<password>&aud=<site_id>&session=[1|0]

this is insecure!

GET requests logged, which reveals the password to everybody who has access to the logs.

Please don't support this insecure way.

**Comment by umputun** [comment]
This is about direct auth provider, not the core part of the service.  Such direct auth is rather a hook for the user to implement whatever method of auth desirable for the particular use-case. As documentation stated "password parameter doesn't have to be naked/real password and can be any kind of password's hash prepared by the caller". In some cases, especially for internal "inside the perimeter"  service-to-service it makes some sense I guess, but either way - this is up to user.

As a side note:  "GET requests logged, which reveals the password to everybody who has access to the logs." sound like too broad statement to me. There is no technical problem to not to log the password as long as user controls the endpoint. On the other hand, sending any sensitive information with POST body doesn't prevent logging. The bottom line - sending anything sensitive to any place may end up in some logs, regardless of which http method was used.

Anyhow, this GET method most like is going to stay, at least for back compatibility. Feel free to submit PR for the docs explaining to the user why this can be potentially dangerous.
