### ISSUE TITLE
Add Mastodon?

### ISSUE THREAD

**Issue by einarpersson** [go-pkgz/auth#137]
In the light of the exodus from Twitter to Mastodon maybe it could be worth doing a push and implementing Mastodon as a provider?

I have only done a little Go last couple of years but could take a look at it if it is of interest (and if I could get some help along the way if necessary).

Note: I come here from https://github.com/umputun/remark42/issues/477

**Comment by paskal** [comment]
Closing in favour of https://github.com/go-pkgz/auth/discussions/136 if you don't mind.
