### ISSUE TITLE
Cannot disable avatar support

### ISSUE THREAD

**Issue by johnlemon93** [go-pkgz/auth#162]
Hi there,

When I tried to set opts.AvatarStore to nil, I got a "nil pointer dereference" exception at https://github.com/go-pkgz/auth/blob/dc03f5df7e6adec282432ed77fc77dae9617f013/provider/service.go#L75
Looks like this is a bug when "nil" of avatar.Proxy is not nil anymore when implicitly cast to AvatarSaver

<img width="870" alt="image" src="https://user-images.githubusercontent.com/10486173/235861243-87e23573-6aaa-40d7-837f-4ba4fa2e1ff8.png">

Expected: the original avatar URL should be kept when the avatar proxy is disabled.

Thanks!

**Comment by umputun** [comment]
I don't this is the right way to disable the avatar store; see [auth.go](https://github.com/go-pkgz/auth/blob/master/auth.go#L63) 

`AvatarStore       avatar.Store // store to save/load avatars, required (use avatar.NoOp to disable avatars support)`

**Comment by johnlemon93** [comment]
Hi @umputun,

I tried that but it still replaced the avatar URL with the proxied one. How can I keep the original URL returned from Google provider?

**Comment by VladimirZaets** [comment]
@johnlemon93 currently it's not supported, u will be able to do that when my PR will be merged https://github.com/go-pkgz/auth/pull/163

**Comment by umputun** [comment]
#163 was merged in
