### ISSUE TITLE
Common shared secret

### ISSUE THREAD

**Issue by umputun** [go-pkgz/auth#30]
Currently, there is a fundamental limitation in a way secret used. Even with [secret reader](https://github.com/go-pkgz/auth/blob/master/token/jwt.go#L52) injected into the token package, it is impossible to use different secrets for different aud values.

In some complex use cases having different secrets will be desirable. For example, if some service issuing tokens for various services or a different group of users, it may be useful to have different keys (secrets) used for withing each group to sigin and verify token.

Currently, it is impossible to do because aud is a part of the claim, and to extract it from jwt without disabling signature validation, this key should be known **before the parsing step**. In other words, we can [make tokens](https://github.com/go-pkgz/auth/blob/master/token/jwt.go#L98) with a custom (per aud) secret, but we can't [parse](https://github.com/go-pkgz/auth/blob/master/token/jwt.go#L130) them without the real secret.

I don't like the idea of the pre-parsing token without signature verification (`jwt.ParseUnverified` can do it) to extract aud first. I'm not sure what issues it may cause, but it feels unusual and (potentially) not secure.

I am trying to figure an alternative method of achieving the goal, i.e. ability to have a secret per aud.

**Comment by cxww107** [comment]
I am not sure if I got you right. But I present you a draft of implementation. there are some points for discussion #35
