### ISSUE TITLE
Support twitter auth

### ISSUE THREAD

**Issue by umputun** [go-pkgz/auth#31]
Twitter's auth is a different beast, but it will be nice to have it integrated

**Comment by cxww107** [comment]
I took a look at Twitter API documentation. it seems that oauth2 is currently only supported for so called [application-only authentication](https://developer.twitter.com/en/docs/basics/authentication/api-reference/token.html).  it can be used for public API requests like get tweet timeline, search for a hashtag etc. but it can not be used for user context requests like read logged-in user profile, settings etc. for that you have to stick with oauth 1a

**Comment by umputun** [comment]
I have checked twitter's auth API a year ago and came to the same conclusion. This ticket actually meant to hide the exotic & unusual quirks of twitter's auth behind our API and internally perform oauth 1.

As far as I recall stdlib doesn't support such oauth flavor, but there are a couple of third-party libraries we can use for this or implement the flow manually.
