### ISSUE TITLE
Undocumented parameter for sendConfirmation

### ISSUE THREAD

**Issue by paskal** [go-pkgz/auth#38]
Hello!

[Lines 141-145 in verify.go](https://github.com/go-pkgz/auth/blob/2734aa35c756c2bf558e35f507eecdbfec1596e0/provider/verify.go#L141-L145) (added in #24):

```go
// GET /login?site=site&&user=name&address=someone@example.com
//<...>
Handshake: &token.Handshake{
	State: "",
	From:  r.URL.Query().Get("from"),
	ID:    user + "::" + address,
},
```

That `from` field reading is not covered by documentation and is not tested. Readme has different signature listed:

```GET /auth/<name>/login?user=<user>&address=<adsress>&aud=<site_id>&from=<url>```

It's not clear to me that this "from" URL parameter is send now (as it called just as `e.sendConfirmation(w, r)` without adding any params), I think code and documentation should be clarified to use it properly or drop it altogether.

**Comment by umputun** [comment]
Likely cut-paste artifact from the primary auth flow. I'll dbl check and remove

**Comment by paskal** [comment]
Another small thing to fix: `/login?site=site&&user=name&address=someone@example.com` occurs twice in the text, `&&` can be replaced  with `&`.

**Comment by umputun** [comment]
can you be more specific pls? occurs where exactly?

**Comment by paskal** [comment]
Same file `verify.go`, lines [62](https://github.com/go-pkgz/auth/blob/2734aa35c756c2bf558e35f507eecdbfec1596e0/provider/verify.go#L62) and [133](https://github.com/go-pkgz/auth/blob/2734aa35c756c2bf558e35f507eecdbfec1596e0/provider/verify.go#L133).
