### ISSUE TITLE
Two suggestions about new auth providers that could be nice to add

### ISSUE THREAD

**Issue by joseph-vidal-rosset** [go-pkgz/auth#39]
https://github.com/umputun/remark/issues/477#issue-520566721

**Comment by umputun** [comment]
Both proposed providers seem to be oauth2, so adding them should be as simple as figuring out configuration details (i.e. urls, scopes, and user info retrieval).

**Comment by joseph-vidal-rosset** [comment]
There is no hurry at all, but many thanks in advance if you do it !

**Comment by robobenklein** [comment]
I'll go ahead and pop in to note that adding twitter and gitlab in addition to mastodon and orcid would allow remark42 to beat just about every other self hosted comments provider (commento, isso, schnack, ...) in terms of social connectivity.

Is all that's needed the oauth details for these or are there code structure changes that need to be made? (I could easily compile the first and add them in a PR if wanted, not sure about the latter)

**Comment by umputun** [comment]
this is what usually involves in adding a new oauth2 provider:

- discover endpoint
- discover the minimal scope for given provider
- add infoURL and provide the matching structure and the mapper
- update `AddProvider` dispatch function https://github.com/go-pkgz/auth/blob/master/auth.go#L204

_see https://github.com/go-pkgz/auth/blob/master/provider/providers.go#L21 for other supported providers_

After this add instruction to readme about the provider

**Comment by umputun** [comment]
no volunteers for this one, and I don't care much about such exotic providers
