### ISSUE TITLE
Proporsal: way to modify Claims during auth process

### ISSUE THREAD

**Issue by vblz** [go-pkgz/auth#50]
What do you think about something like `ClaimsUpd`, but for auth process, for tokens received from clients?

When it could be useful: modifying `Claims` by internal logic.
For example it would be convenient to give admins rights for users with ID from list.

But on the other hand adding this feature will separate token received from client and `Claims` presentation, that's why this might be not really good idea.

**Comment by umputun** [comment]
`CalimsUpd` allows modifying token at the time of generation and refresh. Here [the practical example](https://github.com/umputun/remark42/blob/master/backend/app/cmd/server.go#L868) with ClaimsUpd used to set admin with some internal logic.

The only reason to have similar functionality on the level of `token.ValidatorFunc` (called via auth middleware on each request) I can think of, is to alter claims generated by an external system, not issued but the same producer. I can imagine such cases for inter-service communication, i.e. on service issuing token and hits API of another service, and this another service has to alter the claim somehow. However, all cases I have in mind are better to be handled on the issuer level (if the claim should have admin:true the issuer should make it like this in the first place).

Another problem with this idea is a potential roundtrip to the store on each and every request. Probably can be described in readme, but still, one more place to make it wrong.

**Comment by vblz** [comment]
I solved my issue by wrapping middleware into another middleware, so there is another way to do that.

It had a case described above, there was already finished service and it was easier to make it on our side than another.

And what about a potential roundtrip to the store every request, there is the exactly same situation with `token.ValidatorFunc`, isn't it?

As long there is workaround with wrapping middleware, may be there is no sense in that proposal. So it is at your discretion the issue might be closed.

**Comment by umputun** [comment]
I actually like the idea to provide such functionality as a part of the middleware. Technically speaking, the scope of this claims update has very little to do with auth/tokens, but rather a part of some application-related logic, so middleware seems to be the right place. Another advantage - if we make it as a middleware user could insert updater into particular routes only.

Wanna submit PR with this?
