### ISSUE TITLE
Admin user hasn't admin role

### ISSUE THREAD

**Issue by zebox** [go-pkgz/auth#79]
I use RBAC middleware in my project and when i wrote unit test for rest handler (which wrap in RBAC) my test fall. In test I use basic auth, but var `adminUser` in auth.go hasn't assigned with admin role.

```
// adminUser sets claims for an optional basic auth
var adminUser = token.User{
	ID:   "admin",
	Name: "admin",
        Role: "admin",   // <-- add this
	Attributes: map[string]interface{}{
		"admin": true,
	},

}

```
I suppose if admin flag set true his role have to admin too.

Could you fix it? If are you hasn't free time i will fix and make PR.

**Comment by umputun** [comment]
I don't think this is a bug but rather expected. RBAC is just a middleware checking the role, however, setting the role is the client's responsibility and can be done as a part of the claim's updater. Generally speaking, we don't know what particular roles the user wishes to have and setting "admin" role hardcoded may mismatch with user's roles.

Frankly, I'm not 100% sure about this, but it feels strange to set a role in one and only one particular case.

**Comment by zebox** [comment]
Of course it's not bug. 

You are right about hardcoded, it is very bad practice. But I offer it because see hardcoded Attributes 'admin' field.

I will use claim updater fn in my case.

**Comment by umputun** [comment]
well, the difference here is between attributes, which are supposed to be a mixed bag of things and roles, which supposed to be controlled by the caller. So, it makes some sense, I guess.

I don't like enforcing "admin" attributes either, but needed a way to communicate it back somehow. Probably this wasn't the best solution, but anyway- too late to change it.
