### ISSUE TITLE
Patreon or another donation system

### ISSUE THREAD

**Issue by uPagge** [go-pkgz/auth#89]
I have already partially described the idea in that issue

https://github.com/umputun/remark42/discussions/1034

It would be great to be able to log in through donation services like patreon.

Thus, you can implement the monetization of your project without unnecessary complications. So that only paid subscribers can leave comments.

You could also make a mixture. So that you can log in to paid and free subscribers. But the paid ones would have privileges. For example, somehow highlight their comments. This is especially important for moderators and admins in order to clearly understand who is supporting the project.

You can really think of a lot here.

**Comment by umputun** [comment]
this is an interesting idea. Patreon seems to support oauth2 and adding another provider should be a relatively easy task. Regarding subscriber status, i.e. detection of paying subscribers - this info is hopefully available via some API and we can publish it to some optional JWT claim, and the consumer can detect it and alter the behavior

**Comment by VMAnalytic** [comment]
@umputun Do you mind if I add patreon OAuth provider?

**Comment by umputun** [comment]
not at all, thx

**Comment by umputun** [comment]
done with https://github.com/go-pkgz/auth/pull/95
